### ISSUE TITLE
Query shortest path from ShortestPathSubgraph

### ISSUE THREAD

**Issue by redbug312** [maminrayej/prepona#1]
The [hidden docs](https://docs.rs/prepona/0.1.0/src/prepona/algo/shortest_path/dijkstra.rs.html#103) says there's a method to query shortest path from `ShortestPathSubgraph`,
but there's only a method `distance_to` presented.
It seems difficult to obtain the shortest path without information of `prev`. Is there a way to do this?

Also, the method `distance_to` returns `Option<Magnitude<W>>`.
I wonder if `Magnitude<W>` would be better, with `Magnitude::PosInfinite` replacing for `None`?

**Comment by maminrayej** [comment]
Hi,
Ah, I see how it can be confusing. The documentation means the distance between each pair of vertices.
I'm currently working on my thesis and unfortunately can not spend time on this project. But I'll look into it and if providing `prev` is relatively easy, I'll add it to the next version. Or if you're up to the task, A pull request is always welcome. :)

You're right. It'll be better. I'll implement it in the next version.
